### ISSUE TITLE
iota-pm potentially given invalid startup parameters

### ISSUE THREAD

**Issue by JortdeBokx** [nazarimilad/iota-node#1]
I have noticed that after installing my iota-pm service failed to startup. After inspection I saw that it's startup parameters are `-i http://127.0.0.1:14265 -p 0.0.0.0:8888`. However the protocol definition at the first parameter causes various issues, starting this service with `-i 127.0.0.1:14265 -p 0.0.0.0:8888` works fine.

This issue might be specific to my setup on ubuntu server 16.04.3

**Comment by JortdeBokx** [comment]
Nevermind, It appeared I already had a web service running on port 8888.
sorry for the false alarm

**Comment by nazarimilad** [comment]
No problem. 

In the coming weeks, I will add a mechanism to check if the default ports used in the script for the IRI and other packages such as IOTA-PM aren't already used by other services such as a web server in your case to prevent this kind of problems.

Other improvements such as a TUI and Nelson installation support will be added too.
