### ISSUE TITLE
only recognized 1GB Ram out of 16 when installing

### ISSUE THREAD

**Issue by dansrepo** [nazarimilad/iota-node#2]
Hi, 

Second time I'm installing. This time it gave me a warning about only having 1GB RAM availalble, though this machine has 16GB. 'free' shows me:

              total        used        free      shared  buff/cache   available
Mem:       16340368     3523268    10888220      183040     1928880    12278872
Swap:       4106748           0     4106748

**Comment by nazarimilad** [comment]
It was a stupid error, I just fixed it. Thanks :)
